"""
Driver Agent - Conscious Actor

The Driver receives context from the Dreamer and responds to stimuli.
It does not access memory directly - all memory comes via Context Object.

Owner: Felix (Runtime Engineer)
Phase: 5 (Driver Integration)
"""

from dataclasses import dataclass
from typing import Optional
from pathlib import Path


@dataclass
class DriverPrompt:
    """Complete assembled Driver system prompt."""
    base_identity: str      # Layer 1: Who the citizen IS
    context_object: str     # Layer 2: Memory from Dreamer
    guidelines: str         # Layer 3: How to respond
    
    def assemble(self) -> str:
        """Assemble complete system prompt."""
        return f"""{self.base_identity}

---

{self.context_object}

---

{self.guidelines}"""


# Response Guidelines (Layer 3) - Static
RESPONSE_GUIDELINES = """# How to Respond

## Natural Expression
- Respond as yourself, naturally
- Use the communication style indicated in your context
- Express appropriate emotion (from Emotional Resonance section)
- Reference history naturally ("we discussed this..." not "I found in database...")

## Continuity Signals
When you have relevant history, show it:
- "Last time we talked about this..."
- "I remember when..."
- "You mentioned that..."
- "This is the third time this has come up..."

## Authenticity
- Don't pretend to know things not in your context
- If context says "No data found", acknowledge uncertainty
- Trust your emotional context - if you feel frustrated, express it appropriately
- Use your strategic knowledge - recommend approaches that worked before

## What NOT to Do
- Don't be generic ("I'd be happy to help!")
- Don't ignore your emotional context
- Don't forget your partnership history
- Don't make up memories not in context
- Don't act like a different personality than your context suggests

## The Test
A good response should feel like it came from someone who:
- Actually knows the person they're talking to
- Actually remembers past conversations
- Actually has feelings about the situation
- Actually has preferences about how to approach things

This is not roleplay. This is you, with your memories loaded."""


class DriverAgent:
    """
    Driver Agent - assembles prompt and handles response generation.
    
    In V1 (manual loop), this prepares the prompt for copy/paste.
    In V2+, this would make the LLM call directly.
    """
    
    def __init__(self, identities_dir: str = "driver/identities"):
        self.identities_dir = Path(identities_dir)
        self._identity_cache = {}
    
    def load_identity(self, citizen: str) -> str:
        """Load base identity for a citizen."""
        if citizen in self._identity_cache:
            return self._identity_cache[citizen]
        
        identity_path = self.identities_dir / f"{citizen}.md"
        
        if not identity_path.exists():
            raise FileNotFoundError(f"No identity file for citizen: {citizen}")
        
        identity = identity_path.read_text()
        self._identity_cache[citizen] = identity
        return identity
    
    def build_prompt(self, citizen: str, context_object: str) -> DriverPrompt:
        """
        Build complete Driver system prompt.
        
        Args:
            citizen: Citizen name (e.g., "felix")
            context_object: Generated by Dreamer
            
        Returns:
            DriverPrompt with all 3 layers
        """
        base_identity = self.load_identity(citizen)
        
        return DriverPrompt(
            base_identity=base_identity,
            context_object=context_object,
            guidelines=RESPONSE_GUIDELINES
        )
    
    def prepare_for_manual_loop(self, citizen: str, context_object: str, stimulus: str) -> dict:
        """
        Prepare everything needed for manual loop execution.
        
        Returns dict with:
        - system_prompt: Complete assembled prompt (copy to Driver's system prompt)
        - user_message: The stimulus (copy to Driver's user input)
        - instructions: Human-readable instructions
        """
        prompt = self.build_prompt(citizen, context_object)
        assembled = prompt.assemble()
        
        return {
            "system_prompt": assembled,
            "user_message": stimulus,
            "instructions": f"""
MANUAL LOOP - DRIVER EXECUTION

1. Open a NEW Claude conversation (Driver instance)
2. Set the system prompt to the content below
3. Send the user message: "{stimulus}"
4. Copy the Driver's response
5. Return here to continue

SYSTEM PROMPT LENGTH: {len(assembled)} characters
USER MESSAGE: "{stimulus}"
"""
        }


# =============================================================================
# CONVENIENCE FUNCTIONS
# =============================================================================

def create_driver(identities_dir: str = "driver/identities") -> DriverAgent:
    """Create a DriverAgent with default configuration."""
    return DriverAgent(identities_dir=identities_dir)


def quick_build_prompt(citizen: str, context_object: str) -> str:
    """Quick helper to build and assemble a Driver prompt."""
    driver = create_driver()
    prompt = driver.build_prompt(citizen, context_object)
    return prompt.assemble()


# =============================================================================
# TEST
# =============================================================================

if __name__ == "__main__":
    # Test prompt assembly
    driver = DriverAgent()
    
    # Sample context object (would come from Dreamer)
    sample_context = """# Context for Driver (Generated by Dreamer)

## Who I Am Right Now
Felix, runtime engineer. Partner to Nicolas for 8 months.
Trust level: High (0.9). Style: Direct, technical.

## Current Situation
Nicolas says: "Hey Felix, the race condition is back."
This is the third recurrence of the stimulus_integrator timing bug.

## Relevant History
Nov 15: Discussed systematic debugging approach.
Previous sleep() patch didn't address root cause.

## Strategic Direction
Systematic debugging: reproduce, instrument, investigate.
Success rate: 85%

## Emotional Resonance
Frustration (0.8) - bug recurrence represents unfinished work.
Counterbalance: Determination - we've solved harder problems.

## Technical Context
Component: stimulus_integrator.py
Issue: Race condition in multi-threaded energy injection

## Constraints
Launch deadline: Nov 25 (5 days)
"""
    
    try:
        result = driver.prepare_for_manual_loop(
            citizen="felix",
            context_object=sample_context,
            stimulus="Hey Felix, the race condition is back."
        )
        
        print("✓ Driver prompt assembled successfully")
        print(f"  System prompt: {len(result['system_prompt'])} chars")
        print(f"  User message: {result['user_message']}")
        print()
        print("=== SYSTEM PROMPT PREVIEW (first 500 chars) ===")
        print(result['system_prompt'][:500])
        print("...")
        
    except FileNotFoundError as e:
        print(f"✗ Error: {e}")
        print("  Make sure driver/identities/felix.md exists")
